### ISSUE TITLE
What is the URI of the website?

### ISSUE THREAD

**Issue by wouterbeek** [YASGUI/yasgui.github.io#2]
What is the URI of the website?  I first thought it was https://yasgui.github.io, but that does not exist (404).  Then I thought that it may be http://about.yasgui.org/ (why not HTTPS?), but that did not show the recent content change (i.e., the result of my recently merged commit).

**Comment by LaurensRietveld** [comment]
I've fixed the issue of about.yasgui.org (thats the one ;)) not updating
